# Generated by Django 3.1.7 on 2021-04-08 21:54

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_vacancy_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='vacancy_title', unique=True),
        ),
    ]
